AWSTemplateFormatVersion: 2010-09-09
Description: |
  Static website in EC2
Parameters:
  LatestAmiId:
    Type: AWS::SSM::Parameter::Value<AWS::EC2::Image::Id>
    Default: /aws/service/ami-amazon-linux-latest/al2023-ami-minimal-kernel-default-x86_64
Resources: 
  MecitWepServer:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: !Ref LatestAmiId
      InstanceType: t2.micro
      KeyName: firstkey
      SecurityGroups: 
        - !Ref WebServerSG
      Tags: 
        - Key: Name
          Value: Static-wep-instance
      UserData: 
        Fn::Base64:
          !Sub |
            #! /bin/bash
            dnf update -y
            dnf install httpd -y
            sudo dnf install wget -y
            FOLDER="https://raw.githubusercontent.com/Mecit-tuksoy/my_projects/main/101-kittens-carousel-static-website-ec2/static-web"
            cd /var/www/html
            wget $FOLDER/index.html
            wget $FOLDER/cat0.jpg
            wget $FOLDER/cat1.jpg
            wget $FOLDER/cat2.jpg 
            systemctl start httpd
            systemctl enable httpd  

  WebServerSG:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Enable HTTP for Apache Web Server and SSH for secure connection.
      SecurityGroupIngress: 
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0

