AWSTemplateFormatVersion: 2010-09-09
Description: |
  With this cfn file the static web site is distributed with S3, CloudFront and Route53.
Parameters:

  KittensSubDomainName:
    Description: full domain name like kittens.mecitdevops.com
    Type: String
    AllowedPattern: (?!-)[a-zA-Z0-9-.]{1,63}(?<!-)

Resources:
  MyS3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Ref KittensSubDomainName
      OwnershipControls:
        Rules:
          - ObjectOwnership: BucketOwnerEnforced
      PublicAccessBlockConfiguration:
        BlockPublicAcls: FALSE
      WebsiteConfiguration:
        IndexDocument: index.html
  
  MyS3BucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref MyS3Bucket
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          - Action:
              - 's3:GetObject'
            Effect: Allow
            Resource: !Join
              - ''
              - - 'arn:aws:s3:::'
                - !Ref MyS3Bucket
                - /*
            Principal: '*'

  MyCloudFront:
    Type: AWS::CloudFront::Distribution
    Properties:
      DistributionConfig:
        Aliases: 
          - !Ref KittensSubDomainName
        DefaultCacheBehavior: 
          AllowedMethods: 
            - GET
            - HEAD
          CachePolicyId: 658327ea-f89d-4fab-a63d-7e88639e58f6
          Compress: true
          TargetOriginId: mecit
          ViewerProtocolPolicy: allow-all
        DefaultRootObject: index.html
        Enabled: true
        HttpVersion: http2
        Origins: 
          - CustomOriginConfig: 
              OriginProtocolPolicy: http-only
            DomainName:  !Select [2, !Split ["/", !GetAtt MyS3Bucket.WebsiteURL]]
            Id: mecit
        PriceClass: PriceClass_All
        ViewerCertificate: 
          AcmCertificateArn: arn:aws:acm:us-east-1:238983781593:certificate/01934048-3ffc-44d2-8c9b-3463d17e8373    #your CertificateArn
          MinimumProtocolVersion: TLSv1.2_2021
          SslSupportMethod: sni-only

  MyRoute53:
    Type: AWS::Route53::RecordSetGroup
    Properties:
      HostedZoneId: Z08348542LMKDSH94CCW6    #your HostedZoneId
      RecordSets: 
      - AliasTarget: 
          DNSName: !GetAtt MyCloudFront.DomainName
          HostedZoneId: Z2FDTNDATAQYW2         # CloudFront HostedZoneId
        Name: !Ref KittensSubDomainName
        Type: A

Outputs:
  BucketName: 
    Description: S3 Bucket URL
    Value: !GetAtt MyS3Bucket.WebsiteURL
  CloudfrontEndpoint:
    Description: Cloudfront Endpoint
    Value: !GetAtt MyCloudFront.DomainName
  FullDomainName:
    Description: Full Domain Name of my Application
    Value: !Ref KittensSubDomainName